// <auto-generated />
using Homies.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Homie.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200317055101_AddField")]
    partial class AddField
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Homie.Areas.Series.Models.ArchMovies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Episode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int>("StopPlayMinute")
                        .HasColumnType("int");

                    b.Property<int>("StopPlaySecond")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ArchMovies");
                });

            modelBuilder.Entity("Homie.Areas.Series.Models.Movies", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Archive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Episode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.Property<int>("StopPlayMinute")
                        .HasColumnType("int");

                    b.Property<int>("StopPlaySecond")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
